version: 2.1

aliases:
  - &only-master-filter
    filters:
      branches:
        only:
          - master
  - &ignore-master-filter
    filters:
      branches:
        ignore:
          - master

executors:
  scala-executor:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      SBT_VERSION: 1.3.8
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

commands:
  compile:
    description: Compiles
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Compile
          command: sbt compile
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
  test:
    description: Runs project tests
    steps:
      - run:
          name: Run Tests
          command: sbt test
  version:
    description: if commit warrants version bump, put correct version in version.sbt
    steps:
      - run:
          name: Update Version
          command: |
            export version=$(git log -1 | grep '\[*\]' | cut -d ']' -f1 | cut -d '[' -f2)
            echo $(git log -1)
            sbt 'updateVersion $version'
  publish:
    description: Tag and release to cloudsmith
    parameters:
      cloudsmith-repo:
        type: string
    steps:
      - add_ssh_keys:
            fingerprints:
              - "72:73:52:4d:76:de:58:66:af:29:26:80:57:03:90:87"
      - run:
          name: Publish to cloudsmith
          command: |
            sbt package
            sbt publish
            git config --global user.name 'R&D CI'
            git config --global user.email '<>'
            git commit -am "[ci skip] published exscalabur $(cat version.sbt | cut -d ' ' -f5) to cloudsmith"

jobs:
  tests:
    executor: scala-executor
    steps:
      - checkout
      - compile
      - run:
          name: Run tests
          command: sbt test
  publish-snapshot:
    executor: scala-executor
    steps:
      - checkout
      - compile
      - version
      - publish:
          cloudsmith-repo: https://maven.cloudsmith.io/carta/maven-snapshots
  publish-release:
    executor: scala-executor
    steps:
      - checkout
      - compile
      - version
      - publish:
          cloudsmith-repo: https://maven.cloudsmith.io/carta/maven-releases

workflows:
  branch:
    jobs:
      - tests:
          <<: *ignore-master-filter
  publish-branch:
    jobs:
      - authorize-publish:
          type: approval
          <<: *ignore-master-filter
      - publish-snapshot:
          <<: *ignore-master-filter
          context: org-Global
          requires:
            - authorize-publish

  master:
    jobs:
      - tests:
          <<: *only-master-filter
      - authorize-publish:
          type: approval
          <<: *only-master-filter
      - publish-release:
          <<: *only-master-filter
          context: org-Global
          requires:
            - authorize-publish
            - tests
