version: 2.1

aliases:
  - &only-master-filter
    filters:
      branches:
        only:
          - master
  - &ignore-master-filter
    filters:
      branches:
        ignore:
          - master

executors:
  scala-executor:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      SBT_VERSION: 1.3.8
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

jobs:
  tests:
    executor: scala-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Compile
          command: sbt compile
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run:
          name: Run tests
          command: sbt test

workflows:
  branch:
    jobs:
      - tests:
          <<: *ignore-master-filter

  master:
    jobs:
      - tests:
          <<: *only-master-filter
