name: Snyk monitor - scala

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  snyk-monitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: ""
        env:
          CLOUDSMITH_PIP: ${{ secrets.CLOUDSMITH_PIP }}
          CLOUDSMITH_PIP_TEST: ${{ secrets.CLOUDSMITH_PIP_TEST }}
          CLOUDSMITH_MAVEN_RELEASES: ${{ secrets.CLOUDSMITH_MAVEN_RELEASES }}
      - uses: snyk/actions/setup@master
      - name: Snyk Monitor
        run: snyk monitor --org=transaction-framework --project-name=exscalabur_scala 
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
